[package]
name = "timeline-processor"
edition = "2021"
version = "0.0.1"

[package.metadata.component.target]
world = "timeline-processor"
path = "wit"

[package.metadata.component.target.dependencies."timeline:event-processor-stub"]
path = "wit/deps/timeline_event-processor-stub"

[package.metadata.component.target.dependencies."golem:rpc"]
path = "wit/deps/wasm-rpc"

[package.metadata.component.target.dependencies."timeline:event-processor"]
path = "wit/deps/timeline_event-processor"

[dependencies]
once_cell = "1.17.1"
rand = "0.8.5"

[dependencies.core]
path = "../core"

[dependencies.timeline]
path = "../timeline"

[dependencies.wit-bindgen]
version = "0.17.0"
features = ["realloc"]
default-features = false

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]
required-features = []
