apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: App
spec:
  components:
  - name: timeline-processor
    type: wasm
    properties:
      componentTemplate: rust
    traits:
    - type: wasm-rpc
      properties:
        componentName: event-processor
    - type: wasm-rpc
      properties:
        componentName: timeline-processor
