package timeline:event-processor;

interface api {

  record event {
    time: u64,
    event: list<tuple<string, event-value>>
  }

  variant event-value {
    string-value(string),
    int-value(s64),
    float-value(f64),
    bool-value(bool),
  }

  record worker-id {
    name: string
  }

  record time-period {
    t1: u64,
    t2: u64
  }

  record event-state-result {
    time-period: time-period,
    value: event-value
  }

  record latest-event-to-state-result {
    event-col-name: string,
    event-results: list<event-state-result>
  }

  initialize-latest-event-state: func(worker: worker-id, event-col-name: string) -> result<string, string>;
  add-event: func(event: event) -> result<string, string>;
  latest-event-to-state: func(t1: u64) -> result<latest-event-to-state-result, string>;
}

world event-processor {
  export api;
}
