package timeline:event-processor;

interface api {

  record event {
    time: u64,
    event: list<tuple<string, event-value>>
  }

  variant event-value {
    string-value(string),
    int-value(s64),
    float-value(f64),
    bool-value(bool),
  }

  record worker-id {
    name: string
  }

  initialize: func(worker: worker-id) -> result<string, string>;

  get-events: func() -> list<event>;
}

world event-processor {
  export api;
}
