[workspace]
members = ["timeline", "event-processor", "timeline-processor", "core", "driver", "core-stub", "event-processor-stub", "timeline-processor-stub"]
exclude = ["sample-event-producer", "sample-event-feeder"]
resolver = "2"

[profile.release]
opt-level = "s"
lto = true
