[workspace]
members = ["timeline", "event-processor", "timeline-processor", "core", "driver"]
exclude = ["sample-event-producer", "sample-event-feeder", "benchmark"]
resolver = "2"

[profile.release]
opt-level = "s"
lto = true
