package timeline:core-stub;

interface stub-core {
  use golem:rpc/types@0.1.0.{uri};
  use timeline:core/api.{event-value};
  use timeline:core/api.{event};
  use timeline:core/api.{event-predicate};
  use timeline:core/api.{typed-timeline-result-worker};
  use timeline:core/api.{node-index};
  use timeline:core/api.{server};
  use timeline:core/api.{server-with-event-column-name};
  use timeline:core/api.{timeline-with-server};
  use timeline:core/api.{worker-id};
  use timeline:core/api.{timeline-constant-comparator};
  use timeline:core/api.{timeline-constant-compared};
  use timeline:core/api.{timeline-negated};
  use timeline:core/api.{server-with-event-predicate};
  use timeline:core/api.{server-with-event-predicate-within};
  use timeline:core/api.{timeline-node};
  use timeline:core/api.{timeline-op};

  resource api {
    constructor(location: uri);
    initialize-timeline: func(timeline: timeline-op) -> result<typed-timeline-result-worker, string>;
  }

}

world wasm-rpc-stub-core {
  export stub-core;
}
