apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: App
spec:
  components:
  - name: event-processor
    type: wasm
    properties:
      build:
      - command: cargo component build
        inputs:
        - src
        - wit
        outputs:
        - ../target/wasm32-wasi/debug/event_processor.wasm
      inputWit: wit
      outputWit: wit-generated
      inputWasm: ../target/wasm32-wasi/debug/event_processor.wasm
      outputWasm: ../target/golem-components/event_processor.wasm
    traits:
    - type: wasm-rpc
      properties:
        componentName: core
