package timeline:driver;


interface api {
  use timeline:core-interface/api.{worker-details};

  run: func(core-template-id: string, leaf-template-id: string, event-to-state-template-id: string) -> result<worker-details, string>;
}

world driver {
  export api;
}
