[package]
name = "driver"
version = "0.0.1"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 's'

[dependencies]
timeline-lib = { path = "../timeline-lib" }
raw-events = { path = "../raw-events" }

once_cell = "1.17.1"
rand = "0.8.5"
wit-bindgen = { version = "0.17.0", default-features = false, features = ["realloc"] }

[package.metadata.component.target]
path = "wit"

[package.metadata.component.target.dependencies."golem:timeline"]
path = "wit/deps/timeline"
