apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: App
spec:
  components:
  - name: driver
    type: wasm
    properties:
      componentTemplate: rust
    traits:
    - type: wasm-rpc
      properties:
        componentName: core