//! Kafka producer for timeline events.
//!
//! Publishes events generated by `event-generator` to a Kafka topic.
//! Reusable as a library (for test harness) or as a standalone binary (for cloud).
//!
//! # As a library
//! ```rust,ignore
//! let producer = TimelineKafkaProducer::new("localhost:9092", "timeline-events").await?;
//! producer.publish_session_events("sess-1", &events).await?;
//! ```
//!
//! # As a binary
//! ```bash
//! KAFKA_BROKER=localhost:9092 KAFKA_TOPIC=timeline-events cargo run -p kafka-producer
//! ```

use event_generator::Event;
use rdkafka::producer::{FutureProducer, FutureRecord};
use rdkafka::ClientConfig;
use std::time::Duration;

/// Configuration for the Kafka producer.
pub struct ProducerConfig {
    /// Kafka broker address (e.g., "localhost:9092").
    pub broker: String,
    /// Kafka topic to publish events to.
    pub topic: String,
}

/// Publishes timeline events to Kafka.
pub struct TimelineKafkaProducer {
    _config: ProducerConfig,
    producer: FutureProducer,
    topic: String,
}

impl TimelineKafkaProducer {
    /// Create a new producer connected to the given Kafka broker.
    pub async fn new(broker: &str, topic: &str) -> Result<Self, Box<dyn std::error::Error>> {
        let producer: FutureProducer = ClientConfig::new()
            .set("bootstrap.servers", broker)
            .set("message.timeout.ms", "5000")
            .create()?;

        Ok(Self {
            _config: ProducerConfig {
                broker: broker.to_string(),
                topic: topic.to_string(),
            },
            producer,
            topic: topic.to_string(),
        })
    }

    /// Publish a batch of events for a session.
    ///
    /// Each event is serialized as JSON and published with the session_id as the Kafka key
    /// (ensures all events for a session go to the same partition, preserving order).
    pub async fn publish_session_events(
        &self,
        session_id: &str,
        events: &[Event],
    ) -> Result<(), Box<dyn std::error::Error>> {
        for (i, event) in events.iter().enumerate() {
            let payload = serde_json::to_string(event)?;
            let record = FutureRecord::to(&self.topic)
                .key(session_id)
                .payload(&payload);

            self.producer
                .send(record, Duration::from_secs(5))
                .await
                .map_err(|(err, _)| err)?;

            if (i + 1) % 100 == 0 {
                log::info!(
                    "Session {}: published {}/{} events",
                    session_id,
                    i + 1,
                    events.len()
                );
            }
        }
        Ok(())
    }

    /// Publish events for all sessions generated by the event generator.
    pub async fn publish_all_sessions(
        &self,
        sessions: &[event_generator::GeneratedSession],
    ) -> Result<(), Box<dyn std::error::Error>> {
        for (i, session) in sessions.iter().enumerate() {
            log::info!(
                "Publishing session {}/{}: {} ({} events)",
                i + 1,
                sessions.len(),
                session.session_id,
                session.events.len()
            );
            self.publish_session_events(&session.session_id, &session.events)
                .await?;
        }
        log::info!("All {} sessions published", sessions.len());
        Ok(())
    }
}
