package timeline:rawevents;

interface api {
  use golem:timeline/api.{event-value};

  record event {
    time: u64,
    event: event-value
  }

  add-event: func(order: event) -> ();

  get-event: func(time: u64) -> event;

  get-events: func() -> list<event>;
}

world rawevents {
  export api;
}
