package timeline:rawevents;

interface api {
  record product-item {
    product-id: string,
    name: string,
    price: float32,
    quantity: u32,
  }

  record order {
    order-id: string,
    items: list<product-item>,
    total: float32,
    timestamp: u64,
  }

  add-order: func(order: order) -> ();

  get-events: func() -> list<order>;
}

world rawevents {
  export api;
}
