package timeline:timeline-processor;

interface api {
  use timeline:event-processor/api.{event-value};
  use timeline:event-processor/api.{worker-id};

  initialize-equal: func(child-url: worker-id, current-worker-id: worker-id, event-value: event-value) -> result<string, string>;
}

world timeline-processor {
  import timeline:event-processor-stub/stub-event-processor;
  export api;
}
