package timeline:aggregator;

// See https://component-model.bytecodealliance.org/design/wit.html for more details about the WIT syntax

interface timeline-aggregator-api {
  add: func(value: u64);
  get: func() -> u64;
}

world timeline-aggregator {
  export timeline-aggregator-api;
}
