name: On Demand Benchmark
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [closed]

jobs:
  run-benchmark:
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true || contains(github.event.pull_request.body, '/run-benchmark') }}
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Run Benchmark
        run: |
          echo "Running Benchmark Job"
      - name: Post results as a comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          REPORT="Dummy Benchmark Result"
          COMMENT="### Benchmark Comparison Results\n\n${REPORT}"
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/afsalthaj/golem-timeline/issues/$ISSUE_NUMBER/comments \
          -d '{"body":"Me too"}'
      - name: Copy temporary.json
        run: |
          cp temporary.json benchmark_cold_storage_large.json
      - name: Checkout github_pages
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: EndBug/add-and-commit@v9
        with:
          branch: github_pages
          message: Add benchmark results
          add: benchmark_cold_storage_large.json
          new_branch: github_pages
          push: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
