name: On Demand Benchmark
on:
  issue_comment:
    types: [created]

jobs:
  run-benchmark:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/run-benchmark') }}
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Run Benchmark
        run: |
          echo "Running Benchmark Job"
      - name: Post results as a comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          WORKFLOW_ID: ${{ github.run_id }}
        run: |
          echo "Workflow id is $WORKFLOW_ID";
          REPORT="Dummy Benchmark Result"
          COMMENT="### Benchmark Comparison Results\n\n${REPORT}"
          WORKFLOW_ID=$WORKFLOW_ID
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/afsalthaj/golem-timeline/issues/$ISSUE_NUMBER/comments \
          -d "{\"body\":\"### Cold Storage Large: \n PR Avg Runtime: 94ms, \n Existing Avg Runtime: 100ms \n RunID: $WORKFLOW_ID \"}"
      - name: Copy benchmark result
        env:
          PR_NUMBER: ${{ github.event.issue.number }}
        run: |
          mkdir -p ./benchmark-data
          cp temporary.json benchmark-data/benchmark_cold_storage_large.json
      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.issue.number }}
        run: |
          mkdir -p ./pr
          echo $PR_NUMBER > ./pr/pr_number
      - uses: actions/upload-artifact@v4
        with:
          name: pr_number
          path: pr/
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: benchmark_cold_storage_large.json
          path: benchmark-data/
