name: On Demand Benchmark
on:
  issue_comment:
    types: [created]

jobs:
  run-benchmark:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/run-benchmark') }}
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Run Benchmark
        run: |
          echo "Running Benchmark Job"
      - name: Post results as a comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          REPORT="Dummy Benchmark Result"
          COMMENT="### Benchmark Comparison Results\n\n${REPORT}"
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/afsalthaj/golem-timeline/issues/$ISSUE_NUMBER/comments \
          -d '{"body":"### Cold Storage Large: \n PR Avg Runtime: 94ms, \n Existing Avg Runtime: 100ms"}'
      - name: Copy temporary.json
        run: |
          cp temporary.json benchmark_cold_storage_large.json
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-results-${{ github.event.issue.number }}
          path: |
            benchmark_cold_storage_large.json      
