name: On Demand Benchmark
on:
  issue_comment:
    types: [created]

jobs:
  run-benchmark:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/run-benchmark') }}
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build Benchmark Report Job
        run: |
          echo "Building benchmark report job"
          cargo build --manifest-path=benchmark/Cargo.toml
      - name: Run Benchmark
        run: |
          echo "Running all benchmark jobs and saving to files"
      - name: Post results as a comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          WORKFLOW_ID: ${{ github.run_id }}
        run: |
          #! /bin/bash
        
          # Create a dummy benchmark result
          cp temporary.json benchmark_cold_storage_small.json
          cp temporary.json benchmark_cold_storage_medium.json
          cp temporary.json benchmark_cold_storage_large.json
          
          # Define the files to check
          files=("benchmark_cold_storage_large.json" "benchmark_cold_storage_small.json" "benchmark_cold_storage_medium.json")
          
          # Initialize arrays to store present and absent files
          present_files=()
          absent_files=()
          compare_command="./benchmark/target/debug/benchmark_report compare-benchmarks"
          get_report_command="./benchmark/target/debug/benchmark_report get-report"
          
          echo "Starting to pull the existing benchmark results if exists"
          
           # Check each file
          for file in "${files[@]}"; do
            if git show github_pages:"$file" > "$file.previous"; then
              present_files+=("$file")
              compare_command="$compare_command --files $file=$(pwd)/$file.previous,$(pwd)/$file"
            else
              absent_files+=("$file")
              get_report_command="$get_report_command --files $file=$(pwd)/$file"
            fi
          done
          
          # If there are present files, run the comparison
            if [ ${#present_files[@]} -ne 0 ]; then
               echo "Running comparison with command: $compare_command"
               $compare_command > benchmark_comparison.md
               COMPARISON_MD=$(<benchmark_comparison.md)
               curl -L \
               -X POST \
               -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer $GITHUB_TOKEN" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/afsalthaj/golem-timeline/issues/$ISSUE_NUMBER/comments \
               -d "{\"body\":\"$COMPARISON_MD \n RunID: $WORKFLOW_ID \"}"
            fi
          
          # Process absent files
          if [ ${#absent_files[@]} -ne 0 ]; then
               echo "Running report"
               $get_report_command > report.md
               REPORT_MD=$(<benchmark_comparison.md)
               curl -L \
               -X POST \
               -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer $GITHUB_TOKEN" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/afsalthaj/golem-timeline/issues/$ISSUE_NUMBER/comments \
               -d "{\"body\":\"$COMPARISON_MD \n RunID: $WORKFLOW_ID \"}"
          fi
          
          echo "Done processing files."
      - name: Copy benchmark result
        run: |
          mkdir -p ./benchmark-data
          cp benchmark_cold_storage_large.json benchmark-data/benchmark_cold_storage_large.json
          cp benchmark_cold_storage_small.json benchmark-data/benchmark_cold_storage_small.json
          cp benchmark_cold_storage_medium.json benchmark-data/benchmark_cold_storage_medium.json
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: benchmark_cold_storage_large.json
          path: benchmark-data/
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: benchmark_cold_storage_small.json
          path: benchmark-data/
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: benchmark_cold_storage_medium.json
          path: benchmark-data/

