name: Commit Benchmark Results
on:
  workflow_run:
    workflows: [On Demand Benchmark]
    types:
      - completed

jobs:
  commit-results:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: 'Download artifact'
        uses: actions/github-script@v6
        with:
            script: |
              let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 run_id: ${{ github.event.workflow_run.id }},
              });
              let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
                return artifact.name == "benchmark_cold_storage_large.json"
              })[0];
              let download = await github.rest.actions.downloadArtifact({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 artifact_id: matchArtifact.id,
                 archive_format: 'zip',
              });
              let fs = require('fs');
              fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/benchmark_cold_storage_large.json.zip`, Buffer.from(download.data));
      - name: 'Unzip artifact'
        run: unzip benchmark_cold_storage_large.json.zip

      - name: 'Comment on PR'
        uses: actions/github-script@v6
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              let fs = require('fs');
              let issue_number = fs.readFileSync('./benchmark_cold_storage_large.json');
              console.log(String(issue_number));
      - name: Commit and push benchmark results
        uses: EndBug/add-and-commit@v9
        with:
          pull: true
          branch: github_pages
          message: Add benchmark results
          add: benchmark_cold_storage_large.json
          new_branch: github_pages
          push: true

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
